# Generated by Django 5.2.10 on 2026-02-02 22:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MortalityRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("age", models.IntegerField(db_index=True, unique=True)),
                (
                    "qx_percent",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Probability of death",
                        max_digits=10,
                    ),
                ),
                ("qx_value", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "px_percent",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Probability of survival",
                        max_digits=10,
                    ),
                ),
                ("px_value", models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                "ordering": ["age"],
            },
        ),
    ]
