# Generated by Django 5.2.10 on 2026-02-02 23:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cashflow_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("input_file", models.FileField(upload_to="inputs/data/")),
                ("assumptions_file", models.FileField(upload_to="inputs/assumptions/")),
                (
                    "output_file",
                    models.FileField(blank=True, null=True, upload_to="outputs/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("total_input_rows", models.IntegerField(default=0)),
                ("total_output_rows", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobAssumption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valuation_date", models.DateField()),
                ("discount_rate", models.DecimalField(decimal_places=6, max_digits=10)),
                (
                    "salary_increase_rate",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                ("retirement_age", models.IntegerField()),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assumptions",
                        to="cashflow_api.calculationjob",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeeProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("emp_id", models.CharField(max_length=50)),
                ("emp_name", models.CharField(blank=True, max_length=255, null=True)),
                ("year", models.IntegerField(help_text="Projected Year/Age")),
                (
                    "projected_salary",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "probability_qx",
                    models.DecimalField(decimal_places=6, max_digits=10),
                ),
                (
                    "expected_outflow",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projections",
                        to="cashflow_api.calculationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["emp_id", "year"],
                "indexes": [
                    models.Index(
                        fields=["job", "emp_id"], name="cashflow_ap_job_id_b2ba16_idx"
                    )
                ],
            },
        ),
    ]
