# Generated by Django 5.2.10 on 2026-02-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cashflow_api", "0002_calculationjob_jobassumption_employeeprojection"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprojection",
            name="probability_px",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
    ]
